micronaut:
  http:
    services:
      clinic:
        urls:
          - "${CLINIC_URL}"
        read-timeout: 1s
        connect-timeout: 1s
        connect-ttl: 1s
  application:
    name: alisos
  server:
    port: "${PORT:8080}"